/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LuiIcon {
    }
}
declare global {
    interface HTMLLuiIconElement extends Components.LuiIcon, HTMLStencilElement {
    }
    var HTMLLuiIconElement: {
        prototype: HTMLLuiIconElement;
        new (): HTMLLuiIconElement;
    };
    interface HTMLElementTagNameMap {
        "lui-icon": HTMLLuiIconElement;
    }
}
declare namespace LocalJSX {
    interface LuiIcon {
    }
    interface IntrinsicElements {
        "lui-icon": LuiIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lui-icon": LocalJSX.LuiIcon & JSXBase.HTMLAttributes<HTMLLuiIconElement>;
        }
    }
}
